"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var CheckExecutor_1 = require("./Check/CheckExecutor");
var Check_1 = require("./Check/Check");
var D20AttributeCheck_1 = require("./Check/D20AttributeCheck");
var SimpleCheck_1 = require("./Check/SimpleCheck");
var DieModifier_1 = require("./Check/Modifier/DieModifier");
var ResultModifier_1 = require("./Check/Modifier/ResultModifier");
var TargetModifier_1 = require("./Check/Modifier/TargetModifier");
var Modifier_1 = require("./Check/Modifier/Modifier");
var Die_1 = require("./Die/Die");
var DieBag_1 = require("./Die/DieBag");
module.exports = CheckExecutor_1.CheckExecutor.getInstance();
module.exports.Class = {};
module.exports.Class.Check = Check_1.Check;
module.exports.Class.CheckExecutor = CheckExecutor_1.CheckExecutor.getInstance();
module.exports.Class.D20AttributeCheck = D20AttributeCheck_1.D20AttributeCheck;
module.exports.Class.SimpleCheck = SimpleCheck_1.SimpleCheck;
module.exports.Class.DieModifier = DieModifier_1.DieModifier;
module.exports.Class.ResultModifier = ResultModifier_1.ResultModifier;
module.exports.Class.TargetModifier = TargetModifier_1.TargetModifier;
module.exports.Class.Modifier = Modifier_1.Modifier;
module.exports.Class.Die = Die_1.Die;
module.exports.Class.DieBag = DieBag_1.DieBag;
//# sourceMappingURL=index.js.map