"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var D20AttributeCheck_1 = require("./Check/D20AttributeCheck");
var CheckExecutor_1 = require("./Check/CheckExecutor");
var DieModifierFactory_1 = require("./Check/Modifier/DieModifierFactory");
var DieBag_1 = require("./DieBag");
var check = new D20AttributeCheck_1.D20AttributeCheck(10, 15);
var DMF = new DieModifierFactory_1.DieModifierFactory();
var checker = CheckExecutor_1.CheckExecutor.getInstance();
DMF.setDefaultDieBag(new DieBag_1.DieBag().add(8, 4));
var addDieModifier = DMF.create('assist');
var removeDieModifier = DMF.create('un-assist', { 'remove': 'true', 'phase': 'after' });
removeDieModifier.getDieBag().remove(4, 4);
check.addDieModifier(addDieModifier);
check.addDieModifier(removeDieModifier);
checker.execute(check);
console.log('Did the check pass?  ' + check.isPass());
console.log('Die Report: ' + JSON.stringify(check.getDieBag().report()));
console.log('Check Report: ' + check.report(true));
//# sourceMappingURL=index.js.map